accent = "#7aa2f7"
cursor = "#c0caf5"
foreground = "#a9b1d6"
background = "#1a1b26"
selection_foreground = "#c0caf5"
selection_background = "#7aa2f7"

black = "#32344a"
red = "#f7768e"
green = "#9ece6a"
yellow = "#e0af68"
blue = "#7aa2f7"
magenta = "#ad8ee6"
cyan = "#449dab"
white = "#787c99"
bright_black = "#444b6a"
bright_red = "#ff7a93"
bright_green = "#b9f27c"
bright_yellow = "#ff9e64"
bright_blue = "#7da6ff"
bright_magenta = "#bb9af7"
bright_cyan = "#0db9d7"
bright_white = "#acb0d0"
