accent = "#56949f"
cursor = "#cecacd"
foreground = "#575279"
background = "#faf4ed"
selection_foreground = "#575279"
selection_background = "#dfdad9"

black = "#575279"
red = "#b4637a"
green = "#286983"
yellow = "#ea9d34"
blue = "#56949f"
magenta = "#907aa9"
cyan = "#d7827e"
white = "#faf4ed"
bright_black = "#9893a5"
bright_red = "#b4637a"
bright_green = "#286983"
bright_yellow = "#ea9d34"
bright_blue = "#56949f"
bright_magenta = "#907aa9"
bright_cyan = "#d7827e"
bright_white = "#faf4ed"
