accent = "#7daea3"
cursor = "#bdae93"
foreground = "#d4be98"
background = "#282828"
selection_foreground = "#ebdbb2"
selection_background = "#d65d0e"

black = "#3c3836"
red = "#ea6962"
green = "#a9b665"
yellow = "#d8a657"
blue = "#7daea3"
magenta = "#d3869b"
cyan = "#89b482"
white = "#d4be98"
bright_black = "#3c3836"
bright_red = "#ea6962"
bright_green = "#a9b665"
bright_yellow = "#d8a657"
bright_blue = "#7daea3"
bright_magenta = "#d3869b"
bright_cyan = "#89b482"
bright_white = "#d4be98"
